In [1]:
import numpy as np
k1=np.zeros(10)
k1


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [2]:
k2=np.zeros((3,4))

In [3]:
k2

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [4]:
k3=np.empty((4,6,2))

In [5]:
k3

array([[[  1.48219694e-323,   1.29584327e-272],
        [  9.06757833e-313,   1.72056880e-027],
        [  9.06506704e-313,   1.28014425e-152],
        [  4.87883721e+199,   1.48219694e-323],
        [  4.26614471e+180,   9.06757833e-313],
        [  9.06480111e-313,   1.06757965e+224]],

       [[  6.36598737e-314,   4.94065646e-324],
        [  9.06757833e-313,   6.19633229e+223],
        [  8.78003664e-315,   4.90922779e+252],
        [  6.01346954e-154,   2.54639495e-313],
        [  0.00000000e+000,   0.00000000e+000],
        [  5.98181437e-154,   9.06757833e-313]],

       [[  9.06757833e-313,   9.06757834e-313],
        [  6.36598737e-314,   1.27587155e-152],
        [  9.06757833e-313,   9.06757834e-313],
        [  2.44088554e-154,   2.31650014e-152],
        [  1.91573232e+227,   9.88131292e-324],
        [  6.01346930e-154,   9.06757833e-313]],

       [[  7.08519663e+194,   4.23949547e+175],
        [  4.76660077e+180,   5.30586801e+180],
        [  2.02762986e+174,   2.08

In [6]:
k2=np.zeros((3,4,3))
k2

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [7]:
k3=np.arange(15)
k3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
type(k3)

numpy.ndarray

In [9]:
k4=np.arange(1,15,3)
k4

array([ 1,  4,  7, 10, 13])

In [10]:
k5 = np.arange(10).reshape(2, 5)
k5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
# rw
np.arange(10).reshape(3,5)

ValueError: cannot reshape array of size 10 into shape (3,5)

In [17]:
k6=b = np.zeros_like(k5, float)
k6

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
k6.size

10

In [23]:
# where to use
k6.size()

TypeError: 'int' object is not callable

In [24]:
k7=np.full((3,4,3),6)
k7

array([[[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]])

In [27]:
k7b=np.full((2,4,3,4),7)
k7b

array([[[[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]]],


       [[[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]]]])

In [28]:
k8=np.full_like(k7,8)

In [29]:
k8

array([[[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]])

In [30]:
k9=np.eye(4,4)
k9

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [32]:
# rw
k9b=np.eye(4,3)
k9b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [34]:
k10=np.eye(5,k)
k10

NameError: name 'k' is not defined

In [35]:
k12=np.array([1,2,3],dtype=np.float)
k12
# k12.dtype

array([ 1.,  2.,  3.])

In [38]:
k12.dtype

dtype('float64')

In [39]:
k11=np.array([1,2,3],dtype=np.string_)
k11
k11.dtype

dtype('S1')

In [40]:
k11

array([b'1', b'2', b'3'],
      dtype='|S1')

In [41]:
a1=np.array(np.arange(1,10,2),dtype=np.int64)
a1

array([1, 3, 5, 7, 9], dtype=int64)

In [44]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [45]:
a1.dtype

dtype('int64')

In [46]:
a2=a1.astype(np.float)

In [47]:
a2

array([ 1.,  3.,  5.,  7.,  9.])

In [48]:
a2.dtype

dtype('float64')

In [49]:
a3=a2.astype(np.int32)

In [50]:
a3

array([1, 3, 5, 7, 9])

In [51]:
a3.dtype

dtype('int32')

In [56]:
# re
a4b=a1.astype(np.int32)
a4b

array([1, 3, 5, 7, 9])

In [55]:
a4=a1.astype(np.string_)
a4.dtype
a4

array([b'1', b'3', b'5', b'7', b'9'],
      dtype='|S21')

In [58]:
# rw
a4b=a1.astype(np.string)
a4b.dtype
a4b

AttributeError: module 'numpy' has no attribute 'string'

In [59]:
a5=a4.astype(np.float)
a5.dtype
a5

array([ 1.,  3.,  5.,  7.,  9.])

In [64]:
# rw
from numpy import random as r

In [69]:
# rw
aa6=np.r.randn(4,3)
aa6

AttributeError: module 'numpy' has no attribute 'r'

In [66]:
a6=np.random.randn(4,3)

In [67]:
a6

array([[ 0.51623413,  0.70335728,  1.15764608],
       [ 0.06453069, -0.43223435,  0.06324943],
       [-1.50231746,  0.25737271,  1.0487449 ],
       [-1.21731367,  1.09213696, -0.32194071]])

In [68]:
a6.reshape(3,4)

array([[ 0.51623413,  0.70335728,  1.15764608,  0.06453069],
       [-0.43223435,  0.06324943, -1.50231746,  0.25737271],
       [ 1.0487449 , -1.21731367,  1.09213696, -0.32194071]])

In [90]:
a6-a6

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [ ]:
###### 

In [91]:
a6+a6

array([[-2.95876696, -1.33733791,  1.66452482],
       [ 1.93048095,  2.83750626,  0.42345277],
       [ 0.31120984, -1.74898396,  0.78585935],
       [-0.68309541, -2.60076555, -0.0798495 ]])

In [92]:
a6*a6

array([[  2.18857548e+00,   4.47118174e-01,   6.92660715e-01],
       [  9.31689170e-01,   2.01286045e+00,   4.48280624e-02],
       [  2.42128906e-02,   7.64736224e-01,   1.54393731e-01],
       [  1.16654836e-01,   1.69099536e+00,   1.59398556e-03]])

In [93]:
1/a6

array([[ -0.67595726,  -1.49550834,   1.20154412],
       [  1.03601126,   0.70484426,   4.72307689],
       [  6.42653208,  -1.14352106,   2.54498466],
       [ -2.92784867,  -0.76900434, -25.04712073]])

In [94]:
a6/a6

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [95]:
a6*6

array([[-8.87630088, -4.01201374,  4.99357445],
       [ 5.79144284,  8.51251879,  1.27035831],
       [ 0.93362951, -5.24695188,  2.35757806],
       [-2.04928624, -7.80229664, -0.23954849]])

In [96]:
a6**2

array([[  2.18857548e+00,   4.47118174e-01,   6.92660715e-01],
       [  9.31689170e-01,   2.01286045e+00,   4.48280624e-02],
       [  2.42128906e-02,   7.64736224e-01,   1.54393731e-01],
       [  1.16654836e-01,   1.69099536e+00,   1.59398556e-03]])

In [97]:
a6

array([[-1.47938348, -0.66866896,  0.83226241],
       [ 0.96524047,  1.41875313,  0.21172639],
       [ 0.15560492, -0.87449198,  0.39292968],
       [-0.34154771, -1.30038277, -0.03992475]])