In [1]:
bit.do/noman-islam

NameError: name 'bit' is not defined

In [2]:
import numpy as np

In [6]:
k1=np.random.randn(2,3,4)

In [7]:
k1

array([[[ 1.37157192, -0.32908059,  1.09684281,  0.59313799],
        [ 0.80877641, -0.28427941,  1.36243929, -0.71985477],
        [-0.17854027, -1.17868426,  0.26513909,  0.98228305]],

       [[-0.07066372, -0.00455298,  0.371325  , -1.45489671],
        [ 0.23299278,  1.64254216,  0.41412759,  0.04040663],
        [-0.68994649, -0.83027032,  1.6928486 ,  1.12087786]]])

In [8]:
k2=np.zeros([2,3,4])

In [9]:
k2

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [10]:
k3=np.ones([2,3,4])
k3

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [11]:
k5=np.arange(0,999)

In [12]:
k5

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [13]:
l1=[2,3.2,5.5,-6.4,-2.2,2.4]

In [14]:
a=np.array(l1)

In [15]:
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

In [16]:
a[1]

3.2000000000000002

In [17]:
a[1:4]  

array([ 3.2,  5.5, -6.4])

In [18]:
l2=[2,3.2,5.5,-6.4,-2.2,2.4],[1,22,4,0.1,5.3,-9],[3,1,2.1,21,1.1,-2]

In [19]:
l2

([2, 3.2, 5.5, -6.4, -2.2, 2.4],
 [1, 22, 4, 0.1, 5.3, -9],
 [3, 1, 2.1, 21, 1.1, -2])

In [20]:
a1=np.array(l2)

In [30]:
a1          

array([[  2. ,   3.2,   5.5,  -6.4,  -2.2,   2.4],
       [  1. ,  22. ,   4. ,   0.1,   5.3,  -9. ],
       [  3. ,   1. ,   2.1,  21. ,   1.1,  -2. ]])

In [35]:
a1[:,3] 

array([ -6.4,   0.1,  21. ])

In [37]:
a1[1:4,0:4]

array([[  1. ,  22. ,   4. ,   0.1],
       [  3. ,   1. ,   2.1,  21. ]])

In [22]:
a[:1,2]

IndexError: too many indices for array

In [38]:
j. Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the
variable &quot;arr&quot;.Print the shape of the array. Print the size of the array. Print the maximum and
minimum of the array

SyntaxError: invalid syntax (<ipython-input-38-00f8263c9ddd>, line 1)

In [23]:
l3=list(range(0,4)),list(range(10,14))

In [24]:
l3

([0, 1, 2, 3], [10, 11, 12, 13])

### 

In [25]:
a3=np.array(l3)


In [26]:
a3

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [53]:
l4

[10, 11, 12, 13]

In [27]:
q3=np.array(list(range(0,4)),list(range(10,14)))

TypeError: data type not understood

In [68]:
q3=np.array([range(0,4),range(10,14)])
q3

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [69]:
a3

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [71]:
a3.shape

(2, 4)

In [28]:
a3.size

8

### 

In [29]:
a3.max()

13

In [30]:
a3.min()

0

In [31]:
a3

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [32]:
a3.reshape(2,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [33]:
a3

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [34]:
a3.T

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [39]:
a3.resape(0:9,0:1,0:1)

SyntaxError: invalid syntax (<ipython-input-39-197a028342b1>, line 1)

In [40]:
a3.reshape(8)

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [41]:
a3

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [42]:
a3.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [97]:
a3.dtype(float)

TypeError: 'numpy.dtype' object is not callable

In [98]:
import pandas as pd

In [103]:
x1=pd.Series([1,3,4])

In [101]:
y1=pd.Series([2,3,4,5], Index=[9,8,3,0])

NameError: name 'Index' is not defined

In [104]:
x1.values

array([1, 3, 4], dtype=int64)

In [106]:
x1=pd.Series([2,3,4,5], index=['a','b','c','d'])

In [107]:
x1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [108]:
x1[x1>3]

c    4
d    5
dtype: int64

In [109]:
x1*5

a    10
b    15
c    20
d    25
dtype: int64

In [110]:
4 in x1

False

In [116]:
3 in x1.values

True

In [113]:
x1

a    2
b    3
c    4
d    5
dtype: int64

In [114]:
'a' in x1

True

In [120]:
x1['b']=' '

In [123]:
x1.isnull()

a    False
b    False
c    False
d    False
dtype: bool

In [124]:
x1.notnull()

a    True
b    True
c    True
d    True
dtype: bool

In [135]:
x={
    'name':['noman Islam','alina khan'],
    'age':[36,46],
    'gender':['m','f']
}

In [136]:
df1=pd.DataFrame(x)

# 

In [137]:
df1

age gender         name
0   36      m  noman Islam
1   46      f   alina khan

In [138]:
df1[df1.age>40]

age gender        name
1   46      f  alina khan

In [139]:
df1.loc[0]

age                36
gender              m
name      noman Islam
Name: 0, dtype: object

In [140]:
df1=pd.DataFrame(x),index


NameError: name 'index' is not defined

In [141]:
dframe.age.apply(myfunc)

NameError: name 'dframe' is not defined

In [155]:
def myfunc(age):
    if(age > 18):
        return 'Adult'
    else:
        return ' Not a Adult'

In [159]:
df1.age.apply(myfunc,df1.name.split(' '))

AttributeError: 'Series' object has no attribute 'split'

In [166]:
def lastname(name):
    return name.split()[-1]

In [167]:
df1.name.apply(lastname)

0    Islam
1     khan
Name: name, dtype: object

In [162]:
df1

age gender         name
0   36      m  noman Islam
1   46      f   alina khan