In [1]:
import pandas as pd
import numpy as np


In [2]:
from pandas import Series, DataFrame

In [3]:
from pd import Series, DataFrame

ModuleNotFoundError: No module named 'pd'

In [4]:
obj=pd.Series([4,7,-5,3])



In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2=pd.Series([-5,7,3,6], index=['a','b','c','d'])

In [9]:
obj2.values


array([-5,  7,  3,  6], dtype=int64)

In [10]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [11]:
obj2

a   -5
b    7
c    3
d    6
dtype: int64

In [12]:
obj2['a']
obj2['d']
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2>2]

b    7
c    3
d    6
dtype: int64

In [14]:
obj2*10

a   -50
b    70
c    30
d    60
dtype: int64

In [15]:
obj2

a   -5
b    7
c    3
d    6
dtype: int64

In [16]:
np.exp(obj2)

a       0.006738
b    1096.633158
c      20.085537
d     403.428793
dtype: float64

In [17]:
'b' in obj2


True

In [18]:
sdata={'ohio':35000,'texas':71000,'oregon':16000,'utah':5000}

In [19]:
sdata.keys()

dict_keys(['ohio', 'texas', 'oregon', 'utah'])

In [20]:
obj3=pd.Series(sdata)

In [21]:
obj3

ohio      35000
oregon    16000
texas     71000
utah       5000
dtype: int64

In [22]:
obj3.values

array([35000, 16000, 71000,  5000], dtype=int64)

In [23]:
obj3.index

Index(['ohio', 'oregon', 'texas', 'utah'], dtype='object')

In [24]:
obj3.values

array([35000, 16000, 71000,  5000], dtype=int64)

In [25]:
states=['california', 'ohio', 'oregon', 'texas']

In [26]:
obj4=pd.Series(sdata, index=states)

In [27]:
obj4

california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
dtype: float64

In [28]:
pd.isnull(obj4)

california     True
ohio          False
oregon        False
texas         False
dtype: bool

In [29]:
pd.notnull(obj4)

california    False
ohio           True
oregon         True
texas          True
dtype: bool

In [30]:
obj4.notnull()

california    False
ohio           True
oregon         True
texas          True
dtype: bool

In [31]:
obj3

ohio      35000
oregon    16000
texas     71000
utah       5000
dtype: int64

In [32]:
obj4

california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
dtype: float64

In [33]:
obj4+obj3

california         NaN
ohio           70000.0
oregon         32000.0
texas         142000.0
utah               NaN
dtype: float64

In [34]:
obj4.name= 'population'

In [35]:
obj4.index.name= 'state'

In [36]:
obj4

state
california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
Name: population, dtype: float64

In [37]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [38]:
obj.index=['bob','steve','jeff', 'reyan']

In [39]:
obj

bob      4
steve    7
jeff    -5
reyan    3
dtype: int64

In [40]:
obj4.name()

TypeError: 'str' object is not callable

In [41]:
obj4

state
california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
Name: population, dtype: float64

In [42]:
obj

bob      4
steve    7
jeff    -5
reyan    3
dtype: int64

In [43]:
obj.index=['qasim', 'farooq','ali','kazim']

In [44]:
obj

qasim     4
farooq    7
ali      -5
kazim     3
dtype: int64

dataframe

In [45]:
data={'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
      'year':[2000, 2001, 2002, 2001, 2002, 2003],
      'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
     }

In [46]:
df=pd.DataFrame(data)

In [47]:
df

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [48]:
df.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [49]:
df=pd.DataFrame(data, columns=[ 'year','state', 'pop'])

In [50]:
df

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [51]:
df2=pd.DataFrame(data, columns=['year', 'state','pop','debt'], index=['one','two','three','four','five','six'])

In [52]:
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [53]:
df2.isnull()

year  state    pop  debt
one    False  False  False  True
two    False  False  False  True
three  False  False  False  True
four   False  False  False  True
five   False  False  False  True
six    False  False  False  True

In [54]:
df2.notnull()

year  state   pop   debt
one    True   True  True  False
two    True   True  True  False
three  True   True  True  False
four   True   True  True  False
five   True   True  True  False
six    True   True  True  False

In [55]:
df2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [56]:
df2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [57]:
df2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [58]:
df2.pop

<bound method NDFrame.pop of        year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN>

In [59]:
df2['pop']

one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
six      3.2
Name: pop, dtype: float64

In [60]:
df2.pop

<bound method NDFrame.pop of        year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN>

In [61]:
df2.year.name='qwd'

In [62]:
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

### from Row label (index name)

In [63]:
df2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

## from Row index(number)

In [64]:
df2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

 using list compresion in dictionary coloumn 

In [65]:
df2.debt=[x**3 for x in range(1,7)]


In [66]:
df2

year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     8
three  2002    Ohio  3.6    27
four   2001  Nevada  2.4    64
five   2002  Nevada  2.9   125
six    2003  Nevada  3.2   216

In [67]:
np.arange(5.0)

array([ 0.,  1.,  2.,  3.,  4.])

In [68]:
df2.debt=Nan

NameError: name 'Nan' is not defined

In [69]:
df2

year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     8
three  2002    Ohio  3.6    27
four   2001  Nevada  2.4    64
five   2002  Nevada  2.9   125
six    2003  Nevada  3.2   216

In [70]:
val=pd.Series([1.3,4.3,-5], index=['two', 'five','six'])

In [71]:
df2.debt=val

In [72]:
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7   1.3
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   4.3
six    2003  Nevada  3.2  -5.0

In [73]:
del df2['debt']

In [74]:
df2.columns

Index(['year', 'state', 'pop'], dtype='object')

In [75]:
df2['easter']= df2.state=='Ohio'

## 

In [76]:
df2

year   state  pop  easter
one    2000    Ohio  1.5    True
two    2001    Ohio  1.7    True
three  2002    Ohio  3.6    True
four   2001  Nevada  2.4   False
five   2002  Nevada  2.9   False
six    2003  Nevada  3.2   False

In [77]:
df2.T

one   two three    four    five     six
year    2000  2001  2002    2001    2002    2003
state   Ohio  Ohio  Ohio  Nevada  Nevada  Nevada
pop      1.5   1.7   3.6     2.4     2.9     3.2
easter  True  True  True   False   False   False

loc and iloc


In [78]:
data1=pd.DataFrame(np.arange(16).reshape(4,4),
             columns=['one', 'two', 'three', 'four'],
            index=['Ohio', 'Colorado', 'Utah', 'New York'])

In [79]:
data1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
data1['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [81]:
data1[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [82]:
data1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
data1[0:]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [84]:
data1[data1['three']>6]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [85]:
data1[2:]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [86]:
data1.iloc[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [87]:
data1.iloc[2:]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [88]:
data1.iloc[2,[1,2]]

two       9
three    10
Name: Utah, dtype: int32

In [89]:
data1.loc['Ohio',['two','three']]

two      1
three    2
Name: Ohio, dtype: int32

In [90]:
data1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [91]:
data1.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [92]:
data1.iloc[[2,3], [3, 0, 1]]

four  one  two
Utah        11    8    9
New York    15   12   13

In [93]:
data1=pd.to_excel('C:\Users\wlaik\Documents\A_DrNoman\k33.csv')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-93-2c41e3bddb49>, line 1)

In [94]:
data1.to_csv('examplesout.csv')

In [95]:
data2=pd.read_csv('examplesout.csv')

In [96]:
data2

Unnamed: 0  one  two  three  four
0       Ohio    0    1      2     3
1   Colorado    4    5      6     7
2       Utah    8    9     10    11
3   New York   12   13     14    15

In [97]:
import numpy as np
from numpy import nan as NA
s3 = pd.Series([1, NA, 3.5, NA, 7])

In [98]:
s3

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [99]:
cleaned= s3.dropna()

In [100]:
cleaned

0    1.0
2    3.5
4    7.0
dtype: float64

In [101]:
s4=s3.fillna(90000000000000000)

In [102]:
s4

0    1.000000e+00
1    9.000000e+16
2    3.500000e+00
3    9.000000e+16
4    7.000000e+00
dtype: float64

In [103]:
def func(age):
    if age>18:
        return 'adult'
    else: 
        return 'not an Adult'


In [104]:
x={
    'name':['noman Islam','alina khan'],
    'age':[36,46],
    'gender':['m','f']
}

In [105]:
dfx=pd.DataFrame(x)

In [106]:
dfx

age gender         name
0   36      m  noman Islam
1   46      f   alina khan

In [108]:
dfx.age.apply(func)

0    adult
1    adult
Name: age, dtype: object

In [113]:
def lastname(name):
    return name.split()[-1]



In [115]:
dfx.name.apply(lastname)

0    Islam
1     khan
Name: name, dtype: object

In [ ]:
cc=df1[]