## ndarray

An ndarray is a generic multidimensional container for homogeneous data;

that is, all of the elements must be the same type.

Every array has a shape, a tuple indicating the size of each dimension, 

and a dtype, an object describing the data type of the array

In [15]:
# creating array using np.array function

import numpy as np
data1=[6,7.5,8,0,1]
arr1=np.array(data1)  # converts list into array

In [19]:
# type of arr
type(arr1)

numpy.ndarray

In [18]:
# type on data in array
arr1.dtype   

dtype('float64')

In [20]:
data2=[[1,2,3,4],[5,6,7,8]] #  list of list
arr2=np.array(data2) # 2Darray

In [21]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim # diminsion of array

2

In [22]:
# type of arr2
type(arr2)


numpy.ndarray

In [23]:
arr2.dtype # element's data type

dtype('int32')

## other functions for creating numpy arrray

#### Array  of Zeros

In [28]:
k=np.zeros(10)
k

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
type(k)

numpy.ndarray

In [30]:
k.dtype

dtype('float64')

#### Empty Array

In [33]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [35]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### dtype = defines the data type of elements in array

In [37]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [38]:
np.array([1,2,3,4,5,0],dtype='U')

array(['1', '2', '3', '4', '5', '0'], dtype='<U1')

In [51]:
k=np.array([[True, False],[False,False]])

In [52]:
k.dtype

dtype('bool')

In [55]:
k

array([[ True, False],
       [False, False]])

In [61]:
arr=([1,2,3,4,5])

In [62]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [63]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [65]:
k=np.arange(0,999)

In [66]:
k

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

###  e. Create an array from the list [2, 3.2, 5.5, -6.4, -2.2, 2.4] and assign it to the variable "a"

In [67]:
l=[2, 3.2, 5.5, -6.4, -2.2, 2.4] 

In [70]:
a=np.array(l)

In [71]:
l1

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

### f. Do you know what a[1] will equal? Print it to see

In [72]:
a[1]

3.2

### g. Try printing a[1:4] to see what that equals

In [73]:
a[1:4]

array([ 3.2,  5.5, -6.4])

### h. Create a 2-D array from the following list and assign it to the variable "a":
[[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]]

In [79]:
a=np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]])

In [80]:
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

### i. Can you guess what the following slices are equal to? Print them to check your understanding. a[:, 3] a[1:4, 0:4] a[1:, 2]

In [81]:
a[:3]

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [85]:
a[1:4,0:4]

array([[ 1. , 22. ,  4. ,  0.1],
       [ 3. ,  1. ,  2.1, 21. ]])

### j. Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "arr".Print the shape of the array. Print the size of the array. Print the maximum and minimum of the array

In [90]:
l1=np.arange(4)
l2=np.arange(10,14)

In [95]:
l1

array([0, 1, 2, 3])

In [99]:
arr=np.array([range(4),range(10,14)])

In [100]:
arr

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [101]:
np.max(arr)

13

In [102]:
np.min(arr)

0

### k. Continue to use the array "arr" as defined above.Print the array re-shaped to (2, 2, 2).Print the array transposed.Print the array flattened to a single dimension. Print the array converted to floats.

In [108]:
arr.reshape((2,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [110]:
arr.transpose()

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

### l. Create an an array counting from 1 to 20 inclusive

In [114]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### m. The array of multiples of 3 greater than 0 and less than 30

In [4]:
import numpy as np

In [41]:
i=[2, 3.2, 5.5, -6.4, -2.2, 2.4]

In [42]:
k=np.array(i)

In [43]:
k

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

In [44]:
k[1]

3.2

In [45]:
k[1:4]

array([ 3.2,  5.5, -6.4])

In [46]:
k=[[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]]

In [50]:
aa=np.array(k)
aa

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [52]:
aa[:3]

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [53]:
aa[1:4,0:4]

array([[ 1. , 22. ,  4. ,  0.1],
       [ 3. ,  1. ,  2.1, 21. ]])

In [55]:
aa[1:,2]

array([4. , 2.1])